name: Bet Wars Full-Stack CI/CD 🚀

on:
  push:
    branches: [ main ]

jobs:
  lint-build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # -----------------------------
      # Frontend Lint & Build
      # -----------------------------
      - name: Setup Node for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install Frontend Deps
        working-directory: client
        run: npm ci

      - name: Lint Frontend
        working-directory: client
        run: npm run lint --if-present

      - name: Build Frontend
        working-directory: client
        run: npm run build --if-present

      # -----------------------------
      # Backend Lint
      # -----------------------------
      - name: Install Backend Deps
        working-directory: server
        run: npm ci

      - name: Lint Backend
        working-directory: server
        run: npm run lint --if-present

      # -----------------------------
      # Deploy Backend to Render
      # -----------------------------
      - name: Deploy Backend
        if: github.ref == 'refs/heads/main'
        run: curl -X POST "$RENDER_DEPLOY_HOOK"

      # -----------------------------
      # Deploy Frontend to Vercel
      # -----------------------------
      - name: Deploy Frontend to Vercel
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: client
